---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: kube-system
  labels:
    group: metricbeat
data:
  metricbeat.yml: |-
    metricbeat:
      config:
        modules:
          # Mounted `metricbeat-daemonset-modules` configmap:
          path: ${path.config}/modules.d/*.yml
          # Reload module configs as they change:
          reload:
            enabled: false
      # Hints based autodiscover:
      autodiscover:
         providers:
         - type: kubernetes
           host: ${NODE_NAME}
           hints.enabled: true
    processors:
    - add_cloud_metadata:
    output:
      elasticsearch:
        hosts:
        - "${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}"
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  namespace: kube-system
  labels:
    group: metricbeat
data:
  system.yml: |-
    - module: system
      period: 1m
      metricsets:
      - "cpu"
      - "load"
      - "memory"
      - "network"
      - "process"
      - "process_summary"
      - "core"
      - "diskio"
      - "socket"
      processes:
      - ".*"
      process:
        include_top_n:
          by_cpu: 5
          by_memory: 5
    - module: system
      period: 1m
      metricsets:
      - "filesystem"
      - "fsstat"
      processors:
      - drop_event:
          when:
            regexp:
              system:
                filesystem:
                  mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
      - "node"
      - "system"
      - "pod"
      - "container"
      - "volume"
      period: 1m
      host: ${NODE_NAME}
      hosts:
      - "localhost:10255"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  namespace: kube-system
  labels:
    group: metricbeat
data:
  metricbeat.yml: |-
    metricbeat:
      config:
        modules:
          # Mounted `metricbeat-daemonset-modules` configmap:
          path: ${path.config}/modules.d/*.yml
          # Reload module configs as they change:
          reload:
            enabled: false
      # Hints based autodiscover:
      autodiscover:
         providers:
         - type: kubernetes
           host: ${NODE_NAME}
           hints.enabled: true
    processors:
    - add_cloud_metadata:
    output:
      elasticsearch:
        hosts:
        - "${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}"
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  namespace: kube-system
  labels:
    group: metricbeat
data:
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
      - "state_node"
      - "state_deployment"
      - "state_replicaset"
      - "state_pod"
      - "state_container"
      - "event"
      period: 1m
      host: ${NODE_NAME}
      hosts:
        - "kube-state-metrics:8080"
