---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metricbeat
  namespace: kube-system
  labels:
    group: metricbeat
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      group: metricbeat
      role: monitoring
  template:
    metadata:
      labels:
        group: metricbeat
        role: monitoring
    spec:
      serviceAccountName: metricbeat
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:6.6.2
        args:
        - "-e"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: "/usr/share/metricbeat/metricbeat.yml"
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: "/usr/share/metricbeat/modules.d"
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 384
          name: metricbeat-deployment-config
      - name: modules
        configMap:
          defaultMode: 384
          name: metricbeat-deployment-modules
