---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  labels:
    group: loki
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
