---
images:
  - "gcr.io/$PROJECT_ID/browser-client:latest"
  - "gcr.io/$PROJECT_ID/browser-client:$SHORT_SHA"
timeout: "5m"
steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "cp"
      - "-m"
      - "-r"
      - "gs://artifacts.poutineer.appspot.com/cloudbuild/cache/browser-client/node_modules/"
      - "node_modules/"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/browser-client:latest || exit 0"
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/docker-cloudbuild-browser-client"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "cp"
      - "-r"
      - "-m"
      - "node_modules/"
      - "gs://artifacts.poutineer.appspot.com/cloudbuild/cache/browser-client/node_modules/"
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment
      - browser-client
      - browser-client=gcr.io/$PROJECT_ID/browser-client:$SHORT_SHA
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-west1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=primary-production"
