---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-origin-data
  labels:
    group: couchdb-origin
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/couchdb/"
