# Default values for my-rails-app
replicaCount: 1
image:
  repository: us.gcr.io/experimental-works/blank-rails-api
  tag: 1.0.0
  pullPolicy: IfNotPresent
resources:
  limits:
      cpu: 100m
      memory: 512Mi
  requests:
      cpu: 100m
      memory: 512Mi
