---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    component: node-exporter
    group: prometheus
  name: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      component: node-exporter
      group: prometheus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: node-exporter
        group: prometheus
    spec:
      serviceAccountName: prometheus-node-exporter
      containers:
      - name: prometheus-node-exporter
        image: prom/node-exporter:v0.17.0
        imagePullPolicy: IfNotPresent
        args:
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        ports:
        - name: metrics
          containerPort: 9100
          hostPort: 9100
        resources: {}
        volumeMounts:
        - name: proc
          mountPath: "/host/proc"
          readOnly: true
        - name: sys
          mountPath: "/host/sys"
          readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
      - name: proc
        hostPath:
          path: "/proc"
      - name: sys
        hostPath:
          path: "/sys"
