---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: pushgateway
    group: prometheus
  name: prometheus-pushgateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: alertmanager
    group: prometheus
  name: prometheus-alertmanager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: server
    group: prometheus
  name: prometheus-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: kube-state-metrics
    group: prometheus
  name: prometheus-kube-state-metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: node-exporter
    group: prometheus
  name: prometheus-node-exporter
