apiVersion: v1
kind: Service
metadata:
  name: resources-api
  labels:
    group: resources-api
    role: http-api
    access: external
spec:
  type: ClusterIP
  selector:
    group: resources-api
  ports:
    - name: resources-api-http
      port: 80
      targetPort: 3000
