---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    service: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grafana
      role: browser-application
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: grafana
        role: browser-application
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.4.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: "/etc/grafana/grafana.ini"
          subPath: grafana.ini
        - name: storage
          mountPath: "/var/lib/grafana"
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: administrator
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: GRAFANA_ADMINISTRATOR_PASSWORD
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: "/api/health"
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: "/api/health"
            port: 3000
      volumes:
      - name: config
        configMap:
          name: grafana
      - name: storage
        emptyDir: {}
