---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    service: grafana
    role: browser-application
    access: external
spec:
  type: ClusterIP
  ports:
  - name: grafana-http
    port: 80
    targetPort: 3000
  selector:
    service: grafana
    role: browser-application
