---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    service: grafana
    role: browser-dashboard
spec:
  type: ClusterIP
  ports:
    -
      name: service
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    service: grafana
    role: browser-dashboard
