---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-prometheus-operator
  labels:
    group: grafana
spec:
  selector:
    matchLabels:
      group: grafana
      role: browser-application
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: service
    interval: 30s
    path: "/metrics"
