apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    group: grafana
    role: browser-application
    access: external
spec:
  type: ClusterIP
  selector:
    group: grafana
  ports:
    - name: grafana-http
      port: 80
      targetPort: 3000
