---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    service: metabase
    role: browser-dashboard
spec:
  type: ClusterIP
  ports:
    -
      name: metabase
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    service: metabase
    role: browser-dashboard
