---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: loki
  labels:
    group: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      group: loki
      role: reporting
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        group: loki
        role: reporting
    spec:
      serviceAccountName: loki
      containers:
      - name: loki
        image: grafana/loki:master-b8d81ab
        imagePullPolicy: IfNotPresent
        args:
        - "-config.file=/etc/loki/loki.yaml"
        volumeMounts:
        - name: config
          mountPath: "/etc/loki"
        - name: storage
          mountPath: "/data"
          subPath: 
        ports:
        - containerPort: 3100
      volumes:
      - name: config
        configMap:
          name: loki
      - name: storage
        emptyDir: {}
