# Source: loki/templates/loki/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
    chart: loki-0.1.0
    release: release-name
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      release: release-name
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki
        name: loki
        release: release-name
    spec:
      serviceAccountName: loki
      containers:
        - name: loki
          image: "grafana/loki:master"
          imagePullPolicy: Always
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath:
          ports:
            - name: loki-metrics
              containerPort: 3100
              protocol: TCP
      volumes:
        - name: config
          configMap:
            name: loki
        - name: storage
          emptyDir: {}
