---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: loki
  labels:
    group: loki
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
  - configMap
  - emptyDir
  - persistentVolumeClaim
  - secret
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
