# Source: loki/templates/loki/role.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: loki
  labels:
    app: loki
    chart: loki-0.1.0
    heritage: Tiller
    release: release-name
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: [loki]
