---
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    group: loki
    role: reporting
spec:
  type: ClusterIP
  ports:
  - name: loki-http
    port: 3100
    targetPort: 3100
  selector:
    group: loki
