version: 2
shared:
  dockers:
    ruby: &ruby_docker
      image: "circleci/ruby:2.5"
      environment:
        BUNDLE_JOBS: 8
        BUNDLE_PATH: "./vendor/bundle"
        BUNDLE_RETRY: 2
        ORIGIN_ENCRYPTION_PRIVATE: private
        ORIGIN_ENCRYPTION_SALT: salt
        PGHOST: 127.0.0.1
        PGUSER: poutineer
        PORT: 3000
        RACK_ENV: test
        RACK_SERVICE_TIMEOUT: 25
        RAILS_EMAIL_HOST: localhost
        RAILS_EMAIL_USER: noreply
        RAILS_ENV: "test"
        RAILS_HOST: localhost
        RAILS_MASTER_KEY: private
        RAILS_MAX_THREADS: 2
        RAILS_SESSION_PRIVATE: private
        REDIS_CACHE_POOL_SIZE: 2
        REDIS_CACHE_URL: redis://localhost:6379/0
        REDIS_OBJECTS_POOL_SIZE: 2
        REDIS_OBJECTS_URL: redis://localhost:6379/1
        REDIS_SIDEKIQ_CLIENT_POOL_SIZE: 2
        REDIS_SIDEKIQ_SERVER_POOL_SIZE: 2
        REDIS_SIDEKIQ_URL: redis://localhost:6379/2
        WEB_CONCURRENCY: 2
        WWW_LOCATION: localhost
    node: &node_docker
      image: "circleci/node:8.11"
    postgres: &postgres_docker
      image: "circleci/postgres:10-alpine"
      environment:
        POSTGRES_DB: "poutineer_test"
        POSTGRES_USER: "poutineer"
    redis: &redis_docker
      image: "redis:4.0"
  caches:
    git_save: &git_save
      save_cache:
        key: "poutineer-v2-git-{{ .Branch }}-{{ .Revision }}"
        paths:
          - ".git/"
    git_restore: &git_restore
      restore_cache:
        keys:
          - "poutineer-v2-git-{{ .Branch }}-{{ .Revision }}"
          - "poutineer-v2-git-{{ .Branch }}-"
          - "poutineer-v2-git-"
    bundler_save: &bundler_save
      save_cache:
        key: "poutineer-v2-bundler-{{ .Branch }}-{{ checksum \"Gemfile.lock\" }}"
        paths:
          - "./vendor/bundle"
          - "/usr/local/bundle/config"
    bundler_restore: &bundler_restore
      restore_cache:
        keys:
          - "poutineer-v2-bundler-{{ .Branch }}-{{ checksum \"Gemfile.lock\" }}"
          - "poutineer-v2-bundler-{{ .Branch }}-"
          - "poutineer-v2-bundler-"
    npm_save: &npm_save
      save_cache:
        key: "poutineer-v2-npm-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
        paths:
          - "./node_modules/"
    npm_restore: &npm_restore
      restore_cache:
        keys:
          - "poutineer-v2-npm-{{ .Branch }}-{{ checksum \"package-lock.json\" }}"
          - "poutineer-v2-npm-{{ .Branch }}-"
          - "poutineer-v2-npm-"
workflows:
  version: 2
  core:
    jobs:
      - "browser_setup"
      - "server_setup"
      -
        bundler_audit:
          requires:
            - "server_setup"
      -
        brakeman:
          requires:
            - "server_setup"
      -
        rubocop:
          requires:
            - "server_setup"
      # -
      #   eslint:
      #     requires:
      #       - "browser_setup"
      -
        rspec:
          requires:
            - "browser_setup"
            - "server_setup"
      -
        jest:
          requires:
            - "server_setup"
jobs:
  browser_setup:
    docker:
      - *node_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *git_save
      - *npm_restore
      -
        run:
          name: "Install npm dependencies"
          command: "npm install --no-save"
      - *npm_save
  server_setup:
    docker:
      - *ruby_docker
      - *postgres_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *git_save
      - *bundler_restore
      -
        run:
          name: "Install bundler dependencies"
          command: "bundle check || bundle install"
      - *bundler_save
      -
        run:
          name: "Database Healthcheck"
          command: "dockerize -wait tcp://localhost:5432 -timeout 1m"
      -
        run:
          name: "Adding postgresql to apt sources"
          command: "sudo su -c \"echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list.d/pgdg.list\""
      -
        run:
          name: "Fetching postgresql apt-key"
          command: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"
      -
        run:
          name: "Installing postgres-client"
          command: "sudo apt-get update && sudo apt-get install postgresql-client-10"
      -
        run:
          name: "Load databsase schema"
          command: "bundle exec rake db:create db:structure:load --trace"
  bundler_audit:
    docker:
      - *ruby_docker
      - *postgres_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      -
        run:
          name: "Running bundler-audit"
          command: "bundle exec bundler-audit check --update"
  brakeman:
    docker:
      - *ruby_docker
      - *postgres_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      -
        run:
          name: "Running brakeman"
          command: "bundle exec brakeman"
  rubocop:
    docker:
      - *ruby_docker
      - *postgres_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      -
        run:
          name: "Running rubocop"
          command: "bundle exec rubocop --config .rubocop/config.yml --lint"
  # eslint:
  #   docker:
  #     - *node_docker
  #   steps:
  #     - *git_restore
  #     - "checkout"
  #     - *npm_restore
  #     -
  #       run:
  #         name: "Running eslint"
  #         command: "npm run lint"
  rspec:
    docker:
      - *ruby_docker
      - *postgres_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      - *npm_restore
      -
        run:
          name: "Running RSpec"
          command: "bundle exec rspec --format RspecJunitFormatter --out ./tmp/rspec/rspec.xml --format progress $(circleci tests glob \"spec/**/*_spec.rb\" | circleci tests split --split-by=timings)"
      -
        store_test_results:
          path: "tmp/rspec/"
      -
        store_artifacts:
          path: "tmp/rspec/"
      -
        store_artifacts:
          path: "logs/"
  jest:
    docker:
      - *node_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *npm_restore
      -
        run:
          name: "Running Jest"
          command: "npm run test -- --runInBand --ci --testResultsProcessor='jest-junit'"
          environment:
            JEST_JUNIT_OUTPUT: "tmp/junit/js-test-results.xml"
      -
        store_test_results:
          path: "tmp/junit/"
      -
        store_artifacts:
          path: "tmp/junit/"
      -
        store_artifacts:
          path: "logs/"
