---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  labels:
    group: prometheus-node-exporter
    jobLabel: node-exporter
  name: psp-prometheus-node-exporter
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - prometheus-node-exporter
