---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-coredns
  labels:
    group: prometheus-operator-coredns
    jobLabel: coredns
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9153
    targetPort: 9153
  selector:
    k8s-group: coredns
