---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-kube-scheduler
  labels:
    group: prometheus-operator-kube-scheduler
    jobLabel: kube-scheduler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    targetPort: 10251
  selector:
    k8s-group: kube-scheduler
  type: ClusterIP
