---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  labels:
    group: kibana
data:
  kibana.yml: |
    elasticsearch.url: http://elasticsearch-master:9200
    server.host: "0.0.0.0"
    server.name: kibana
