---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    group: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      group: kibana
      role: browser-application
  template:
    metadata:
      labels:
        group: kibana
        role: browser-application
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.6.2
        env:
        - name: server.host
          value: 0.0.0.0
        volumeMounts:
        - name: kibana
          mountPath: "/usr/share/kibana/config/kibana.yml"
          subPath: kibana.yml
        ports:
        - containerPort: 5601
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          httpGet:
            path: "/app/kibana"
            port: 5601
      volumes:
      - name: kibana
        configMap:
          name: kibana
