---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    group: kibana
    role: browser-application
    access: external
spec:
  type: ClusterIP
  selector:
    group: kibana
  ports:
    - name: http
      port: 80
      targetPort: 5601
