---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-origin
  labels:
    service: postgresql-origin
    role: database
spec:
  type: ClusterIP
  ports:
  - name: postgresql-origin
    port: 5430
    targetPort: 5432
  selector:
    service: postgresql-origin
    role: database
