---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-operator-prometheus-config
  labels:
    group: prometheus-operator-prometheus
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
