---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleList
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-operator-prometheus
    labels:
      group: prometheus-operator-prometheus
    namespace: kube-system
  rules:
  - apiGroups:
    - ''
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: prometheus-operator-prometheus
    labels:
      group: prometheus-operator-prometheus
    namespace: default
  rules:
  - apiGroups:
    - ''
    resources:
    - nodes
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
