---
apiVersion: v1
kind: Service
metadata:
  name: resources-api
  labels:
    service: resources-api
    role: http-api
    access: external
spec:
  type: ClusterIP
  selector:
    service: resources-api
  ports:
  - port: 80
    targetPort: 3000
