---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    service: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      service: metabase
      role: browser-application
  template:
    metadata:
      labels:
        service: metabase
        role: browser-application
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:v0.30.1
        imagePullPolicy: IfNotPresent
        env:
        - name: MB_JETTY_HOST
          value: 0.0.0.0
        - name: MB_JETTY_PORT
          value: '3000'
        - name: MB_DB_TYPE
          value: postgres
        - name: MB_DB_DBNAME
          value: metabase
        - name: MB_DB_PASS
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: POSTGRES_METABASE_PASSWORD
        - name: MB_DB_HOST
          value: pgbouncer.default
        - name: MB_DB_PORT
          value: 5432
        - name: MB_PASSWORD_COMPLEXITY
          value: normal
        - name: MB_PASSWORD_LENGTH
          value: '12'
        - name: JAVA_TIMEZONE
          value: UTC
        - name: MB_EMOJI_IN_LOGS
          value: 'true'
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: "/"
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: "/"
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources: {}
