apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    group: metabase
    role: browser-application
    access: external
spec:
  type: ClusterIP
  selector:
    group: metabase
  ports:
    - name: metabase-http
      port: 80
      targetPort: 3000
