default: &default
  adapter: postgresql
  uri: <%= ENV.fetch("DATABASE_URL") %>
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
  prepared_statements: false
  advisory_locks: false
  variables:
    statement_timeout: "15s"
    lock_timeout: "15s"

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
