development:
  www_origin: http://www.poutineer.local
  resources_origin: http://resources.poutineer.local
  discovery_origin: http://discovery.poutineer.local
  cdn_origin: http://cdn.poutineer.local
  rails:
    max_threads: 1
    min_threads: 1
    web_concurrency: 1
    cookie_key: "_blank_api_rails"
    email_default: noreply@poutineer.local
    host: poutineer.local
    servce_static_files: false
    port: 3001
  devise:
    email_default: noreply@poutineer.local
  redis:
    sidekiq_client:
      pool: 10
    sidekiq_server:
      pool: 10
    cache:
      pool: 20
    lock:
      pool: 20
    objects:
      pool: 20
  sidekiq:
    killswitch:
      queues: []
      workers: []
  rack:
    timeout:
      service_timeout: 100000
  postgres:
    statement_timeout: "10s"
    lock_timeout: "5s"
production:
  www_origin: https://www.poutineer.com
  resources_origin: https://resources.poutineer.com
  discovery_origin: https://discovery.poutineer.com
  cdn_origin: https://cdn.poutineer.com
  rails:
    max_threads: 1
    min_threads: 10
    web_concurrency: 2
    cookie_key: "_poutineer"
    email_default: noreply@poutineer.com
    host: poutineer.com
    servce_static_files: false
    port: 3001
  devise:
    email_default: noreply@poutineer.com
  redis:
    sidekiq_client:
      pool: 20
    sidekiq_server:
      pool: 20
    cache:
      pool: 20
    lock:
      pool: 20
    objects:
      pool: 20
  sidekiq:
    killswitch:
      queues: []
      workers: []
  rack:
    timeout:
      service_timeout: 20
  postgres:
    statement_timeout: "10s"
    lock_timeout: "5s"
