---
apiVersion: v1
kind: Service
metadata:
  name: resource-api
  labels:
    service: resource-api
    role: http-api
    access: external
spec:
  type: ClusterIP
  selector:
    service: resource-api
  ports:
  - name: http
    port: 80
    targetPort: 3000
