---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-configuration
  labels:
    group: pgbouncer
data:
  userlist.txt: |-
    "postgres" "md5b612ae8c26dc79943c79e40b1fe6b4a4"
    "application" "md51db0f223a36c93367be2b672dc042c57"
    "pgbouncer" "md5f10c9a6b4703affe7518401dd9f75f69"
    "sentry" "md5ad1a87c1eb47af87d0ff3ec94278f947"
    "metabase" "md50a12f7c044bc38f6718a032631cb0c71"
  pgbouncer.ini: |-
    [databases]
    * = host=postgresql-origin port=5430 auth_user=postgres

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 5432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    logfile = /dev/stdout
    admin_users = postgres
    stats_users = postgres
    default_pool_size = 20
    max_client_conn = 100
    max_db_connections = 0
    min_pool_size = 0
    pool_mode = transaction
    reserve_pool_size = 0
    reserve_pool_timeout = 5
    query_timeout = 0
    ignore_startup_parameters = extra_float_digits
