---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    service: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pgbouncer
      role: load-balancer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: pgbouncer
        role: load-balancer
    spec:
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer:1.9.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgbouncer-configuration
          mountPath: "/etc/pgbouncer"
          readOnly: true
        livenessProbe:
          tcpSocket:
            port: 5432
          periodSeconds: 60
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - killall -INT pgbouncer && sleep 120
      volumes:
      - name: pgbouncer-configuration
        configMap:
          name: pgbouncer-configuration
