---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-operator
  labels:
    group: prometheus-operator-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator-operator
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-operator-pod-security
  labels:
    group: prometheus-operator-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-operator-pod-security
subjects:
- kind: ServiceAccount
  name: prometheus-operator-operator
  namespace: default
