---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-operator
  labels:
    group: prometheus-operator-operator
spec:
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      group: prometheus-operator-operator
  namespaceSelector:
    matchNames:
    - default
