---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-kube-controller-manager
  labels:
    group: prometheus-operator-kube-controller-manager
    jobLabel: kube-controller-manager
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    targetPort: 10252
  selector:
    k8s-group: kube-controller-manager
  type: ClusterIP
