---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    service: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  resources-api
      prefix: /resources/
      service: resources-api.default
spec:
  selector:
    access: external
  ports:
  - name: ambassador
    port: 80
    targetPort: http
