---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cache-data
  labels:
    group: redis-cache
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/redis/"
