---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cache-data
  labels:
    group: redis-cache
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
