---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-origin-data
  labels:
    group: redis-origin
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/redis/"
