---
apiVersion: v1
kind: Service
metadata:
  name: redis-origin
  labels:
    group: redis-origin
    role: database
spec:
  type: ClusterIP
  selector:
    group: redis-origin
  ports:
  - name: redis-tcp
    port: 6379
    targetPort: 6379
