---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-origin-data
  labels:
    service: redis-origin
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
