---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-origin-data
  labels:
    service: redis-origin
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/tmp/redis/data"
