---
apiVersion: v1
kind: Service
metadata:
  name: redis-origin
  labels:
    service: redis
    role: database
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    service: redis
    role: database
