# Default values for blank-api-rails
replicaCount: 1
image:
  repository: us.gcr.io/experimental-works/blank-api-rails
  tag: 1.0.0
  pullPolicy: IfNotPresent
resources:
  limits:
      cpu: 100m
      memory: 512Mi
  requests:
      cpu: 100m
      memory: 512Mi
