---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana
  labels:
    group: grafana
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
