---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-origin
  labels:
    service: postgresql-origin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgresql-origin
      role: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: postgresql-origin
        role: database
    spec:
      containers:
      - name: postgresql-origin
        image: postgres:11.2
        imagePullPolicy: IfNotPresent
        command:
        - docker-entrypoint.sh
        - "-c"
        - config_file=/var/lib/postgresql/configuration/postgresql.conf
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-origin-data
          mountPath: "/var/lib/postgresql/data/"
        - name: postgresql-origin-configuration
          mountPath: "/var/lib/postgresql/configuration/"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: "/var/lib/postgresql/data/"
      volumes:
      - name: postgresql-origin-data
        persistentVolumeClaim:
          claimName: postgresql-origin-data
      - name: postgresql-origin-configuration
        secret:
          secretName: postgresql-origin-configuration
