---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-origin-data
  labels:
    group: postgresql-origin
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/tmp/postgresql/"
