---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-origin-configuration
  labels:
    service: postgresql-origin
type: Opaque
stringData:
  postgresql.conf: |-
    listen_addresses = '*'
    port = 5432
    max_connections = 500
    shared_buffers = 256MB
    effective_cache_size = 768MB
    maintenance_work_mem = 64MB
    dynamic_shared_memory_type = posix
    checkpoint_completion_target = 0.7
    wal_buffers = 7864kB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 524kB
    min_wal_size = 1GB
    max_wal_size = 2GB
    log_timezone = 'UTC'
    datestyle = 'iso, mdy'
    timezone = 'UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
    shared_preload_libraries = 'pg_stat_statements.so'
