---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-origin
  labels:
    group: postgresql-origin
    role: database
spec:
  type: ClusterIP
  selector:
    group: postgresql-origin
  ports:
  - name: postgresql-postgres
    port: 5430
    targetPort: 5432
