---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-admin
  labels:
    service: ambassador-admin
    role: browser-dashboard
    access: external
spec:
  type: NodePort
  ports:
  - name: admin
    port: 8877
    targetPort: admin
  selector:
    service: ambassador
