---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-router
  labels:
    service: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  resources-api
      prefix: /resources/
      service: resources-api.default
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  grafana
      prefix: /grafana/
      service: grafana.default
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  metabase
      prefix: /metabase/
      service: metabase.default
spec:
  selector:
    access: external
  ports:
  - name: ambassador-router
    port: 80
    targetPort: http
