---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    service: ambassador
    role: service-mesh
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  root
      prefix: /
      service: metabase.default
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  resources-api
      prefix: /resources/
      service: resources-api.default
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  grafana
      prefix: /grafana/
      service: grafana.default
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  metabase
      prefix: /metabase/
      service: metabase.default
spec:
  type: LoadBalancer
  selector:
    service: ambassador
    role: service-mesh
  ports:
  - name: ambassador-http
    port: 80
    targetPort: 80
