---
apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-database-initialize
  labels:
    service: sentry
spec:
  template:
    metadata:
      name: release-name-db-init
      labels:
        app: release-name-sentry
        release: release-name
    spec:
      restartPolicy: Never
      containers:
      - name: sentry-database-initialize
        image: sentry:9.0
        command:
        - sentry
        - upgrade
        - "--noinput"
        env:
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: SENTRY_SECRET
        - name: SENTRY_DB_NAME
          value: sentry
        - name: SENTRY_DB_USER
          value: sentry
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: POSTGRES_SENTRY_PASSWORD
        - name: SENTRY_POSTGRES_HOST
          value: pgbouncer.default
        - name: SENTRY_POSTGRES_PORT
          value: '5432'
        - name: SENTRY_REDIS_HOST
          value: redis-origin.default
        - name: SENTRY_REDIS_PORT
          value: '6379'
        - name: SENTRY_EMAIL_HOST
          value: smtp
        - name: SENTRY_EMAIL_PORT
          value: '25'
        - name: SENTRY_EMAIL_USER
          value: sentry
        - name: SENTRY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: SENTRY_EMAIL_PASSWORD
        - name: SENTRY_EMAIL_USE_TLS
          value: 'false'
        - name: SENTRY_SERVER_EMAIL
          value: sentry@blank-api-rails.com
        - name: GITHUB_APP_ID
          value: ''
        - name: GITHUB_API_SECRET
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: GITHUB_API_SENTRY_SECRET
        volumeMounts:
        - mountPath: "/etc/sentry"
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: sentry-configuration
---
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-user-create
  labels:
    app: release-name-sentry
    chart: sentry-1.3.0
    release: release-name
    heritage: Tiller
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: '5'
spec:
  template:
    metadata:
      name: sentry-user-creation
      labels:
        service: sentry
    spec:
      restartPolicy: Never
      containers:
      - name: user-create-job
        image: sentry:9.0
        command:
        - sentry
        - createuser
        - "--no-input"
        - "--email"
        - admin@sentry.local
        - "--superuser"
        - "--password"
        - "$(SENTRY_USER_PASSWORD)"
        env:
        - name: SENTRY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: SENTRY_USER_PASSWORD
        - name: SENTRY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: SENTRY_SECRET
        - name: SENTRY_DB_NAME
          value: sentry
        - name: SENTRY_DB_USER
          value: sentry
        - name: SENTRY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: POSTGRES_SENTRY_PASSWORD
        - name: SENTRY_POSTGRES_HOST
          value: pgbouncer.default
        - name: SENTRY_POSTGRES_PORT
          value: '5432'
        - name: SENTRY_REDIS_HOST
          value: redis-origin.default
        - name: SENTRY_REDIS_PORT
          value: '6379'
        - name: SENTRY_EMAIL_HOST
          value: smtp
        - name: SENTRY_EMAIL_PORT
          value: '25'
        - name: SENTRY_EMAIL_USER
          value: sentry
        - name: SENTRY_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: SENTRY_EMAIL_PASSWORD
        - name: SENTRY_EMAIL_USE_TLS
          value: 'false'
        - name: SENTRY_SERVER_EMAIL
          value: sentry@blank-api-rails.com
        - name: GITHUB_APP_ID
          value: ''
        - name: GITHUB_API_SECRET
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: GITHUB_API_SENTRY_SECRET
        volumeMounts:
        - mountPath: "/etc/sentry"
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: sentry-configuration
