---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentry-data
  labels:
    service: sentry
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/tmp/sentry/data"
