apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-data
  labels:
    group: sentry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
