---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-data
  labels:
    service: sentry
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
