---
apiVersion: v1
kind: Service
metadata:
  name: sentry
  labels:
    service: sentry
    role: browser-application
    access: external
spec:
  type: ClusterIP
  selector:
    service: sentry
  ports:
  - name: sentry-http
    port: 80
    targetPort: 9000
