apiVersion: v1
kind: Service
metadata:
  name: sentry
  labels:
    group: sentry
    role: browser-application
    access: external
spec:
  type: ClusterIP
  selector:
    group: sentry
  ports:
    - name: sentry-http
      port: 80
      targetPort: 9000
