---
images:
  - "gcr.io/experimental-works/blank-api-rails:latest"
  - "gcr.io/experimental-works/blank-api-rails:$SHORT_SHA"
timeout: "5m"
steps:
  -
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull gcr.io/experimental-works/blank-api-rails:latest || exit 0"
  -
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/docker-cloudbuild"
    env:
      - "SHORT_SHA=$SHORT_SHA"
      - "PROJECT_ID=$PROJECT_ID"
    secretEnv:
      - "RAILS_MASTER_KEY"
secrets:
  -
    kmsKeyName: "projects/experimental-works/locations/global/keyRings/blank-api-rails/cryptoKeys/runtime-secrets"
    secretEnv:
      RAILS_MASTER_KEY: "CiQALYc+q9UWcq3393OZXLPsPSkK858pPbauNJaOZsmomeHaJcwSSgCedma4YMFBtcajg+xN0Uw3nta7svJ3r0dAZP3996f4TH9xE91G7fZT85xG1aHX1bP46zeGglm5tDY1GvitDxhzXrOdR9cLFx4L"
