---
images:
  - "gcr.io/experimental-works/blank-api-rails:latest"
timeout: "5m"
steps:
  -
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull gcr.io/experimental-works/blank-api-rails:latest || exit 0"
  -
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "bin/docker-cloudbuild $$SHORT_SHA"
    env:
      - "SHORT_SHA=$$SHORT_SHA"
      - "PROJECT_ID=$$PROJECT_ID"
    secretEnv:
      - "RAILS_MASTER_KEY"
secrets:
  -
    kmsKeyName: "projects/experimental-works/locations/global/keyRings/blank-api-rails-build-secrets/cryptoKeys/RAILS_MASTER_KEY"
    secretEnv:
      RAILS_MASTER_KEY: "CiQACNX132sxiLVZiqIzp486GA7HrSnh3AQ/z4OqJbUnKQigrBwSSgA1CizuIAUxsww8YjL2Tz/fjydb11MQ2Z7Z8gAYAGaf0rWvSNTRn4fxZpp8/z18Cwq8y2Tm3WTUQ7SLo/zRmNoHzKd6vX8AyZ4D"
