---
images:
  - "gcr.io/$PROJECT_ID/blank-api-rails:latest"
timeout: "5m"
steps:
  -
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/blank-api-rails:latest || exit 0"
  -
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/blank-api-rails:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/blank-api-rails:latest"
      - "--file"
      - "./docker/production/Dockerfile"
      - "."
