---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    group: promtail
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      group: promtail
      role: monitor
  template:
    metadata:
      labels:
        group: promtail
        role: monitor
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: grafana/promtail:master-b8d81ab
        imagePullPolicy: IfNotPresent
        args:
        - "-config.file=/etc/promtail/promtail.yaml"
        - "-client.url=http://loki.default:3100/api/prom/push"
        volumeMounts:
        - name: config
          mountPath: "/etc/promtail"
        - name: varlog
          mountPath: "/var/log"
        - name: containers
          mountPath: "/var/lib/docker/containers"
          readOnly: true
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
          runAsUser: 0
      volumes:
      - name: config
        configMap:
          name: promtail
      - name: varlog
        hostPath:
          path: "/var/log"
      - name: containers
        hostPath:
          path: "/var/lib/docker/containers"
