---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador-deployment
  labels:
    service: ambassador
    role: gateway
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        "consul.hashicorp.com/connect-inject": "false"
      labels:
        service: ambassador
        role: gateway
    spec:
      restartPolicy: Always
      containers:
        -
          name: ambassador
          image: quay.io/datawire/ambassador:0.50.2
          resources:
            limits:
              cpu: 1
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 100Mi
          env:
            -
              name: AMBASSADOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            -
              name: http
              containerPort: 80
            -
              name: https
              containerPort: 443
            -
              name: admin
              containerPort: 8877
          livenessProbe:
            httpGet:
              path: /ambassador/v0/check_alive
              port: 8877
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ambassador/v0/check_ready
              port: 8877
            initialDelaySeconds: 30
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-service
  labels:
    service: ambassador
    role: gateway
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   -
     port: 80
  selector:
    service: ambassador
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-admin-service
  labels:
    service: ambassador-admin
    role: dashboard
spec:
  type: NodePort
  ports:
    -
      name: ambassador-admin
      port: 8877
      targetPort: 8877
  selector:
    service: ambassador-admin
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-router-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  resource-api-mapping
      prefix: /api/
      service: resource-api-service
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  kubernetes-dashboard-mapping
      prefix: /k8s/
      service: kubernetes-dashboard-service
spec:
  selector:
    access: external
  ports:
    -
      name: ambassador-router-service
      port: 80
      targetPort: http
