---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  labels:
    service: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pgbouncer
      role: load-balancer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: pgbouncer
        role: load-balancer
    spec:
      containers:
        -
          name: pgbouncer
          image: edoburu/pgbouncer:1.9.0
          imagePullPolicy: IfNotPresent
          ports:
            -
              containerPort: 5432
          env:
            -
              name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: POSTGRES_PASSWORD
            -
              name: DB_HOST
              value: "postgresql-origin"
            -
              name: POOL_MODE
              value: session
            -
              name: MAX_CLIENT_CONN
              value: "100"
            -
              name: SERVER_RESET_QUERY
              value: DISCARD ALL
          livenessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "killall -INT pgbouncer && sleep 120"
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  labels:
    service: pgbouncer
    role: load-balancer
spec:
  type: ClusterIP
  ports:
    -
      name: pgbouncer
      port: 5431
      targetPort: 5432
  selector:
    service: pgbouncer
    role: load-balancer
