---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-origin
  labels:
    service: postgresql-origin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgresql-origin
      role: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: postgresql-origin
        role: database
    spec:
      containers:
        -
          name: postgresql-origin
          image: postgres:10.6
          imagePullPolicy: IfNotPresent
          ports:
            -
              containerPort: 5432
          volumeMounts:
            -
              name: postgresql-origin-data
              mountPath: /var/lib/postgresql/data
          env:
            -
              name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: POSTGRES_PASSWORD
            -
              name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        -
          name: postgresql-origin-data
          persistentVolumeClaim:
            claimName: postgresql-origin-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-origin
  labels:
    service: postgresql-origin
    role: database
spec:
  type: ClusterIP
  ports:
    -
      name: postgresql-origin
      port: 5432
      targetPort: 5432
  selector:
    service: postgresql-origin
    role: database
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-origin-data
  labels:
    service: postgresql-origin
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/postgresql/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-origin-data
  labels:
    service: postgresql-origin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
