---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-api-deployment
  labels:
    service: resource-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      service: resource-api
      role: http-api
  template:
    metadata:
      labels:
        service: resource-api
        role: http-api
    spec:
      imagePullSecrets:
        -
          name: gcr-json-key
      containers:
        -
          name: resource-api
          image: gcr.io/experimental-works/blank-api-rails:latest
          imagePullPolicy: Always
          ports:
            -
              name: http
              containerPort: 3000
          env:
            -
              name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: DATABASE_URI
            -
              name: REDIS_SIDEKIQ_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_SIDEKIQ_URI
            -
              name: REDIS_OBJECTS_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_OBJECTS_URI
            -
              name: REDIS_CACHE_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_CACHE_URI
            -
              name: REDIS_LOCK_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_LOCK_URI
            -
              name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: RAILS_MASTER_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: resource-api-service
  labels:
    service: resource-api
    role: http-api
spec:
  type: LoadBalancer
  selector:
    service: resource-api
  ports:
    -
      name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: resource-api-job-database-migration
  labels:
    service: resource-api
    role: postdeploy
spec:
  completions: 1
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        -
          name: resource-api-database-migration
          image: gcr.io/experimental-works/blank-api-rails:latest
          args:
            - "bin/rake"
            - "db:create"
            - "db:migrate"
          env:
            -
              name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: DATABASE_URI
            -
              name: REDIS_SIDEKIQ_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_SIDEKIQ_URI
            -
              name: REDIS_OBJECTS_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_OBJECTS_URI
            -
              name: REDIS_CACHE_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_CACHE_URI
            -
              name: REDIS_LOCK_URI
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: REDIS_LOCK_URI
            -
              name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: RAILS_MASTER_KEY
